### ISSUE TITLE
Update NPM package

### ISSUE THREAD

**Issue by rummik** [cheery/node-udev#10]
A checkout of the repository shows version `0.1.5`, which compiles and runs in Node 5.4.1, however `0.1.3` is the latest release in NPM.

**Comment by cheery** [comment]
npmjs has recently updated their usernames to require lowercase letters only, so I was unable to fix this.

I'm waiting for npm to respond on my support request.

**Comment by cheery** [comment]
npmjs support helped to resolve my problem with usernames, and I finally fixed this.

Thanks for informing me out on this. I'll try make it so that people wouldn't need to tell me to npm publish on the projects that I am not actively working on anymore.
