### ISSUE TITLE
v8::ObjectTemplate::Set() with non-primitive values is deprecated

### ISSUE THREAD

**Issue by matianfu** [cheery/node-udev#15]
Got this warning in Node.js 6.6.0, Ubuntu 16.04.

**Comment by cheery** [comment]
[This issue elsewhere](https://github.com/Automattic/node-canvas/issues/758) proposes that update of nan -package will fix this.

**Comment by nbroeking** [comment]
Is there an update or a fix for this?

**Comment by cheery** [comment]
No current plans if the fix does not work. Anyone willing to fix this issue has free hands to do so and put a pull request.

**Comment by cheery** [comment]
@matianfu, @nbroeking  nan package version was bumped up and it fixed the #17 

I also ran `npm publish`. Might not fix anything here but good thing to try.

When I run `npm install udev`, it warns about `TryCatch` deprecated. It's not a big thing so I let it be for now.

**Comment by nbroeking** [comment]
@cheery  Thank you! I tested it this morning. Everything works great.

**Comment by cheery** [comment]
@nbroeking If anything else goes bad, file a new issue. Thanks for checking.
