### ISSUE TITLE
Reimplementation in N-API

### ISSUE THREAD

**Issue by cheery** [cheery/node-udev#33]
As a response to discussion on the issue #32, we examine the possibility to reimplement the library with N-API. The motivation to do this change is that this interface is purported to be [ABI-stable](https://nodejs.org/api/n-api.html#n_api_implications_of_abi_stability).

The secondary objective here is to also provide WebIDL specifications and TypeScript headers for the library, to allow easier interop from numerous languages that compile to Js.

This change is allowed to be backwards-breaking, and we will bump up the version number by major. Still the library users are considered. We will document why the interface changes, for each function. We also attempt to keep the new library useful for the same things the previous library was useful for.

Resources for the project:

 1. [N-API documentation](https://nodejs.org/api/n-api.html). Outright it seems quite good, easy to comprehend and comprehensive documentation for the library.
 2. [WebIDL spec](https://heycam.github.io/webidl/#introduction).
 3. [WebIDL wikipedia entry](https://en.wikipedia.org/wiki/Web_IDL).
 4. [WebIDL binding generator](https://github.com/nodejs/node-addon-api/issues/294) an experimental tool to generate bindings from the WebIDL specs. I'm planning to examine this one and see how well it fares.

A new branch [(v1)](https://github.com/cheery/node-udev/tree/v1) was created for the work toward the N-API bindings. Help is welcome and we will work on this together.

**Comment by GaikwadPratik** [comment]
@cheery,

Thank you for taking initiative to create this ticket. I know all of us are busy. Just wanted to check if there is any progress on this since node v10 is EOL and is not being supported anymore

**Comment by GaikwadPratik** [comment]
@cheery ,

when are you going to release the package in nom?

**Comment by cheery** [comment]
I'm going to release npm later this week.

ti 27. heinäk. 2021 klo 14.43 Gaikwad Pratik ***@***.***>
kirjoitti:

**Comment by GaikwadPratik** [comment]
@cheery,

any idea when would you be releasing it in nom?

**Comment by cheery** [comment]
I did run npm publish during the weekend. Anything elsewhere that is needed?

ti 10. elok. 2021 klo 18.03 Gaikwad Pratik ***@***.***>
kirjoitti:
