### ISSUE TITLE
unref assertion failing in some versions of libudev

### ISSUE THREAD

**Issue by alejandroclaro** [cheery/node-udev#37]
Looks like there is an incorrect reference counting management with libudev in line 180 of udev.cc

![image](https://user-images.githubusercontent.com/6095662/152898543-238e3068-1c88-4c46-9d82-a7a614fc0016.png)

According to the documentation: 

https://manpages.debian.org/testing/libudev-dev/udev_device_get_parent.3.en.html

The function `udev_device_get_parent` do not increment the reference, and the child node have a reference to the returned device. In some version of libudev, this triggers an assertion and the program is aborted:

```
Assertion 'p->n_ref > 0' failed at src/libudev/libudev-device.c:502, function udev_device_unref(). Aborting.
```

Changing the code around line 180 to this seems to fix the issue:

```c
  udev_device *parentDev = udev_device_get_parent(dev.get());

  if (!parentDev) {
    return env.Null();
  }

  Napi::Object obj = Napi::Object::New(env);
  PushProperties(env, obj, parentDev);
  const char *path = udev_device_get_syspath(parentDev);
```

**Comment by alejandroclaro** [comment]
Pull request with a proposed fix: `fix bad udev_device_get_parent unref` #38

**Comment by cheery** [comment]
Hi, I applied your patch and published it. We're done here, I guess?

**Comment by alejandroclaro** [comment]
Thanks @cheery we will test it again.

**Comment by alejandroclaro** [comment]
@cheery I can confirm it's working now. We have been testing for some days and everything is fine now. Thanks!
