### ISSUE TITLE
Assertion `handle->InternalFieldCount() > 0' failed.

### ISSUE THREAD

**Issue by birdca** [cheery/node-udev#5]
It works fine while I use the [how-to-use example](https://github.com/cheery/node-udev#how-to-use) after ```npm install udev```, but will meet error like
```void node::ObjectWrap::Wrap(v8::Handle<v8::Object>): Assertion `handle->InternalFieldCount() > 0' failed.```
```Aborted (core dumped)``` 
after clone source code, ```npm i``` and node the [example](https://github.com/cheery/node-udev#how-to-use).

OS: Ubuntu 14.04 64bits
nodejs: 1.2.0
npm: 2.5.1
libudev1: 204-5ubuntu20.11

**Comment by cheery** [comment]
I may have forgotten to update the npmjs, but if it's related to recent changes, it would break when I republish. 

Did you typo the nodejs: 1.2.0? I thought the newest is 0.12.4.

**Comment by cheery** [comment]
I don't manage to reproduce the error. Also I just compared the tarball and the git repository.

The major difference is this in package.json: 

    <     "nan": "~1.7.0"
    ---
    >     "nan": "~1.8.4"

I bumped the version in npmjs.

**Comment by birdca** [comment]
Yeah, it might be typo, but I can't reconfirm it now.

Same error on different computer:
OS: Ubuntu 14.04 64bits
nodejs: 0.10.38
npm: 1.4.28
libudev1: 204-5ubuntu20.12
I think it's not a installation problem. That's okay, I'll try to figure it out~ Thank u!

**Comment by birdca** [comment]
Oooops! It was my mistake, sorry...
After I change `var udev = require('./build/Release/udev');` to `var udev = require("./udev");` in my test, it works!!
I totally forgot that it'll show "Cannot find module 'udev'", so I changed `var udev = require("udev");` to `var udev = require('./build/Release/udev');`, really sorry about that! :p

**Comment by cheery** [comment]
Why did that cause to abort on assertion rather than crash properly? Also can you think of a modification into the program that'd have prevented this mistake? After all it took you 3 days to figure it out.

I already know one possible way, but you might know better one.

**Comment by birdca** [comment]
M.. it's a tough question, actually I'm new to js (only 1 month), could you show me some tips?

**Comment by cheery** [comment]
Actually I think these simple modifications would have helped:

* Create examples/ -directory, have require('../udev') on them.
* Put the example in README into examples/, inform that it is there.
